# This is a basic workflow to help you get started with Actions

name: Main Delivery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Development:

    runs-on: ubuntu-latest
    environment: Development
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: Publish
        run: |
          dotnet restore ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj
          dotnet build ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj --configuration Release
          dotnet publish ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj -c Release -o 'Clean.Architecture.Template.Api/Release'

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'Clean.Architecture.Template.Api/Release' 
          
  Staging:
    needs: [ Development ]
    runs-on: ubuntu-latest
    environment: Staging
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
        
      - name: Publish
        run: |
          dotnet restore ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj
          dotnet build ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj --configuration Release
          dotnet publish ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj -c Release -o 'Clean.Architecture.Template.Api/Release'

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'Clean.Architecture.Template.Api/Release' 

  Production:
    needs: [ Staging ]
    runs-on: ubuntu-latest
    environment: Staging
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
        
      - name: Publish
        run: |
          dotnet restore ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj
          dotnet build ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj --configuration Release
          dotnet publish ./src/Clean.Architecture.Template.Api/Clean.Architecture.Template.Api.csproj -c Release -o 'Clean.Architecture.Template.Api/Release'

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'Clean.Architecture.Template.Api/Release' 
