# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the workflow will run
on: 
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore: 
      - main

jobs:
  pull-request:

    runs-on: ubuntu-latest
    environment: Development
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  
